//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int qid { get; set; }
        public string quiz_name { get; set; }
        public string qdesc { get; set; }
        public string opt1 { get; set; }
        public string opt2 { get; set; }
        public string opt3 { get; set; }
        public string opt4 { get; set; }
        public int ans { get; set; }
    }
}
